set(_CATKIN_CURRENT_PACKAGE "quadruped_monitoring")
set(quadruped_monitoring_VERSION "0.0.0")
set(quadruped_monitoring_MAINTAINER "user <user@todo.todo>")
set(quadruped_monitoring_PACKAGE_FORMAT "2")
set(quadruped_monitoring_BUILD_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(quadruped_monitoring_BUILD_EXPORT_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(quadruped_monitoring_BUILDTOOL_DEPENDS "catkin")
set(quadruped_monitoring_BUILDTOOL_EXPORT_DEPENDS )
set(quadruped_monitoring_EXEC_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(quadruped_monitoring_RUN_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(quadruped_monitoring_TEST_DEPENDS )
set(quadruped_monitoring_DOC_DEPENDS )
set(quadruped_monitoring_URL_WEBSITE "")
set(quadruped_monitoring_URL_BUGTRACKER "")
set(quadruped_monitoring_URL_REPOSITORY "")
set(quadruped_monitoring_DEPRECATED "")