set(_CATKIN_CURRENT_PACKAGE "quadruped_real")
set(quadruped_real_VERSION "0.0.0")
set(quadruped_real_MAINTAINER "user <user@todo.todo>")
set(quadruped_real_PACKAGE_FORMAT "2")
set(quadruped_real_BUILD_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(quadruped_real_BUILD_EXPORT_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(quadruped_real_BUILDTOOL_DEPENDS "catkin")
set(quadruped_real_BUILDTOOL_EXPORT_DEPENDS )
set(quadruped_real_EXEC_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(quadruped_real_RUN_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(quadruped_real_TEST_DEPENDS )
set(quadruped_real_DOC_DEPENDS )
set(quadruped_real_URL_WEBSITE "")
set(quadruped_real_URL_BUGTRACKER "")
set(quadruped_real_URL_REPOSITORY "")
set(quadruped_real_DEPRECATED "")